### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-visual-pathway-editor#1]
Todos

- [x] On the “molecule” pop-up box (both first-time entry, and in edit mode), add one more annotation line, where someone can add “located in” CC (same autocomplete as “occurs in” CC in activity pop-up, excluding complexes). The model would create molecule located-in CC. No additional evidence is required for this.
- [ ] ~On the “relation” pop-up box (in edit mode, when I’m editing a relation that I created earlier), it currently doesn’t allow me to edit the evidence. Please enable this editing.~ replaced by #9 
- [ ] ~On the activity editing pop-up, if there’s no BP and I’m adding one, please add to the autocomplete all the BPs that are already in the model.~ See  #9
- [x] Make a complex the enabler of an activity - done in #2
- [x] edit panel for an activity “enabled by GP” box UNDER the MF box error
- [x] Add cc and bp on the box
- [ ] ~undo/redo~ see #11

**Comment by pgaudet** [comment]
@tmushayahama 

I think this is superseded by the other tickets I created yesterday?

**Comment by pgaudet** [comment]
Closing, we have tickets for each of the remaining items
